module Assets.Image.Types
  ( Image(..)
  ) where

data Image =
    Img100
  | Img1000
  | Img200
  | Img400
  | Img500
  | ImgBlock1
  | ImgBlock2
  | ImgBlock3
  | ImgBlock4
  | ImgBlock5
  | ImgBroken
  | ImgCloud00
  | ImgCloud01
  | ImgCloud02
  | ImgCloud10
  | ImgCloud11
  | ImgCloud12
  | ImgCoin0
  | ImgCoin1
  | ImgCoin2
  | ImgCoin3
  | ImgDk00
  | ImgDk01
  | ImgDk10
  | ImgDk11
  | ImgFire0
  | ImgFire1
  | ImgFire2
  | ImgFire3
  | ImgFlag
  | ImgFlower
  | ImgFNarioLJump
  | ImgFNarioLShot
  | ImgFNarioLSit
  | ImgFNarioLSlip
  | ImgFNarioLStand
  | ImgFNarioLWalk1
  | ImgFNarioLWalk2
  | ImgFNarioLWalk3
  | ImgFNarioRJump
  | ImgFNarioRShot
  | ImgFNarioRSit
  | ImgFNarioRSlip
  | ImgFNarioRStand
  | ImgFNarioRWalk1
  | ImgFNarioRWalk2
  | ImgFNarioRWalk3
  | ImgFont
  | ImgGrass0
  | ImgGrass1
  | ImgGrass2
  | ImgKinoko
  | ImgKoura
  | ImgKoura2
  | ImgKuri0
  | ImgKuri1
  | ImgKuriDead
  | ImgMt02
  | ImgMt11
  | ImgMt12
  | ImgMt13
  | ImgMt22
  | ImgNarioDead
  | ImgNarioLJump
  | ImgNarioLSlip
  | ImgNarioLStand
  | ImgNarioLWalk1
  | ImgNarioLWalk2
  | ImgNarioLWalk3
  | ImgNarioRJump
  | ImgNarioRSlip
  | ImgNarioRStand
  | ImgNarioRWalk1
  | ImgNarioRWalk2
  | ImgNarioRWalk3
  | ImgNokoL0
  | ImgNokoL1
  | ImgNokoR0
  | ImgNokoR1
  | ImgPole0
  | ImgPole1
  | ImgSNarioLJump
  | ImgSNarioLSit
  | ImgSNarioLSlip
  | ImgSNarioLStand
  | ImgSNarioLWalk1
  | ImgSNarioLWalk2
  | ImgSNarioLWalk3
  | ImgSNarioRJump
  | ImgSNarioRSit
  | ImgSNarioRSlip
  | ImgSNarioRStand
  | ImgSNarioRWalk1
  | ImgSNarioRWalk2
  | ImgSNarioRWalk3
  | ImgTitle
  deriving (Eq, Show)
